### PR TITLE
Adding the timer supplier capability

### PR DESCRIPTION
**Pull request by waleed-dawood**

### CODE REVIEW

**Comment by rudgirello** [comment]
Why would this be needed? What is the use case?

**Comment by waleed-dawood** [comment]
Metrics in dropwizard library is pretty customizable but monitoring center is not as customize-able. Talking specifically about Timer, with the current code in monitoring-center you can not customize timer and all the timers are created with ExponentiallyDecayingReservoir. Drop-wizard provides following additional implementations of the reservoir : 
 
UniformReservoir
SlidingWindowReservoir
SlidingTimeWindowReservoir 

Going back to ExponentiallyDecayingReservoir, the docs say 

> An exponentially-decaying random reservoir of longs. Uses Cormode et al's forward-decaying priority reservoir sampling method to produce a statistically representative sampling reservoir, exponentially biased towards newer entries.

This makes ExponentiallyDecayingReservoir well suited for high frequency events (API response timers etc). It is not suitable for timing events that happen less frequently e.g. 5 mins or 1 hour etc. With ExponentiallyDecayingReservoir the mean, p50, p99 are essentially all the same (or very close to the same) value. If you try to calculate mean, p50, p99 from just 2 values, the results are not very meaningful. 

For less frequent events SlidingWindowReservoir or SlidingTimeWindowReservoir. Will be much more beneficial.

**Comment by rudgirello** [comment]
I see. MonitoringCenter is just as customizable. The extension point that you are looking for is the MetricCollector::registerMetric(Metric metric, String topLevelName, String... additionalNames). That is, you instantiate whatever type of Timer, Meter, or Histogram you'd like and pass it in to registerMetric().

**Comment by waleed-dawood** [comment]
The problem with MetricCollector::registerMetric(Metric metric, String topLevelName, String... additionalNames) is that internally it calls MetricRegistry::register(String name, T metric)
which throws  IllegalArgumentException("A metric named " + name + " already exists") if the metric already exists so one has to be careful not register the same metric twice.


current client code : 
```
abcTimer = metricCollector.getTimer("abc")
```
New code (with register):
```
Timer timer = new Timer(new SlidingWindowReservoir(100));
metricCollector.registerMetric(timer,"abc");
abcTimer = metricCollector.getTimer("abc");
```

New code (with PR changes):

```
abcTimer = metricCollector.getTimer("abc", new Timer(new SlidingWindowReservoir(100)))
```

Not only the register code is uglier but if that block is executed more than once it will throw an exception. Which yields complicated code around metrics. 

Dropwizard has a nice (logical getOrAdd ) method for all the metrics where you don't have to worry about if the metric is already created/registered. Monitoring center is already doing this but only with a single default implementation.

**Comment by rudgirello** [comment]
Generally, the idea is that you register your metrics first and then you use them. If you are worrying about double instantiation, then it's a problem by itself in your code design. This could cause very hard-to-catch bugs. IMHO, it's logical to re-register a metric anew in case its hold class/service is being re-instantiated. If you expect your MetricCollector to be used in such a way, then before registering any metrics with it, call removeAll(). Alternatively, there's an option to call replaceMetric() which is a shortcut for remove and register.

That is, the usage pattern, given your example would be as follows.
In your service constructor, for instance:
metricCollector.replaceMetric(new Timer(new SlidingWindowReservoir(100)), "abc");
And then in places of usage:
abcTimer = metricCollector.getTimer("abc");

However, a much cleaner and more logical way would be to do the following:
In your service constructor, for instance:
this.timer = new Timer(new SlidingWindowReservoir(100));
metricCollector.replaceMetric(this.timer, "abc");

And then in places of usage:
this.timer

**Comment by waleed-dawood** [comment]
You said
> Generally, the idea is that you register your metrics first and then you use them.

I beg to differ. While the register functionality is there, Dropwizard's MetricRegistry and MonitoringCenter's MetricCollector both are designed around "return if present, create and register new metric if not present". This is especially true for common metrics like Timer,Counter,Histogram etc.

From the docs:
MetricRegistry(Dropwizard)
> Return the Timer registered under this name; or create and register a new Timer if none is registered.

MetricCollector(MonitoringCenter) : 
> Retrieves a timer, creating it if one does not exist. 

I strongly believe the same behavior should be there if one is just trying to use a customized Timer.

Also, Drop-wizard's MetricRegistry already provides the supplier functionality not only for Timer but also for Counter,Histogram,Meter & Gauge. 

Lastly the suggestion you presented at the end will not work because whenever I create a new instance of the service the timer instance on all the previously created instances become unregistered/invalid, which is undesirable.  It is a very valid scenario where I have more than instance of a service but want to get metrics on every call to a certain method of that service.

**Comment by rudgirello** [comment]
- Yes, the get* methods provide that convenience by convention. However, for instance, in case of the Gauge, there's no such option and you must call register. Calling get("name", supplier or new instance) is dirty and confusing, in my opinion. If you think about it logically, you are saying "get me an instance of what I am supplying as parameter anyway".
- Supplying a custom instance of Timer in every client call is a terrible idea, as then you have code duplication and potential for bugs. That is why I strongly recommend first registering the metrics and then using the instance fields. Consider the situation where you have two calls to getTimer in your service: getTimer( "abc", new Timer(new SlidingWindowReservoir(100)) and getTimer("abc", new Timer(new UniformReservoir())). Order of execution will determine which one gets registered and returned for both calls. This is obviously a bad practice.
- I still insist that if you have multiple instances of your class/service and they are using the same metric, there's likely a design flaw in your code architecture. If these instances have semantic differences, I'd suggest using a namespace: registerMetric(customTimer, "abc", "ns"). If these instances are workers or spendable instances, in other words, then such common metrics must be managed outside of these instances and supplied as parameters to them (constructor, DI, or outer class field access, for example). 
- In high performance code, you are also creating an extraneous instance, allocating memory needlessly.

**Comment by waleed-dawood** [comment]
- For the gauge the option is there, at least in Dropwizard. https://metrics.dropwizard.io/4.0.0/apidocs/com/codahale/metrics/MetricRegistry.html#gauge-java.lang.String-com.codahale.metrics.MetricRegistry.MetricSupplier-

- Your example here makes perfect sense and people can always use a library wrong. However IMHO MonitoringCenter is built on top of dropwizard and it should not take away functionality present/allowed in dropwizard. Especially considering the fact that it does not allow access to the underlying metric registry. 
- You said
> I still insist that if you have multiple instances of your class/service and they are using the same metric, there's likely a design flaw in your code architecture. (...) If these instances are workers or spendable instances, in other words, then such common metrics must be managed outside of these instances and supplied as parameters to them (constructor, DI, or outer class field access, for example).

I would respectfully disagree. As I mentioned in the last comment it is a valid scenario where one has more than one instance of a service but they want to get metrics on every call to a certain method of that service. To make things concrete please consider following code : 

```java
public class DeepThoughtService {
    private static final MetricCollector metricCollector = MonitoringCenter.getMetricCollector(DeepThoughtService.class);
    private Timer myTimer;

    public DeepThoughtService() {
        this.myTimer = metricCollector.getTimer("meaningOfLifeTimer");
    }

    public int getMeaningOfLife() {
        int meaningOfLife = 0;
        try (Timer.Context timerContext = myTimer.time()) {
            //calculate
            meaningOfLife = 42;
        }
        return meaningOfLife;
    }
}
```
Now this is a very valid usage of Timer. Please advise on design flaws if there are any. It seems cumbersome that the metric needs to be managed out of this class if one just wants to customize it. Now whatever way one might use to implement this (with `register` method approach) it will create one nuisance or the other e.g. injecting the metric in constructor causes the issue of (one way or the other) having your own registry of the metric.

**Comment by rudgirello** [comment]
The design flaw here is that it only makes sense to have a single instance of this service in the JVM. Having more I'd consider a design flaw--instead it should be instantiated once and re-used. Like I said above, there're valid possibilities for multiple instances: semantically different classes and worker-like instances. I've provided suggestions for both.

Either way to satisfy you as the avid client of my library, I've implemented support for get* methods with supplier. Please use version 1.0.16. FYI, in your PR the deficiency was that you a) only updated getTimer, leaving the other methods confusingly without the overload; b) omitted null checks for suppliers; c) utilized the MetricRegistry's internal supplier class, leaking more DropWizard internal classes to client of the lib.

**Pull request closed without merging**
